/* CARDS & CARDS CLICKED */
export const RECEIVE_CARDS = 'RECEIVE_CARDS'
export const FLIP_CARD = 'FLIP_CARD'
export const TURN_CARDS_OVER = 'TURN_CARDS_OVER'
export const REMOVE_MATCH = 'REMOVE_MATCH'

/* DIFFICULTY */
export const SELECT_DIFFICULTY = 'SELECT_DIFFICULTY'

/* SCORE */
export const UPDATE_SCORE = 'UPDATE_SCORE'

/* TIME */
export const SET_TIME = 'SET_TIME'

/* ENTIRE STATE */
export const RESET_GAME_STATE = 'RESET_GAME_STATE'
