/* CARDS */
export const RECEIVE_CARDS = 'RECEIVE_CARDS';
export const FLIP_CARD = 'FLIP_CARD';
export const REMOVE_MATCH = 'REMOVE_MATCH';

/* CARDS CLICKED */
export const RESET_CARDS_CLICKED = 'RESET_CARDS_CLICKED';
export const TURN_TWO_CARDS_OVER = 'TURN_TWO_CARDS_OVER';

/* DIFFICULTY */
export const SELECT_DIFFICULTY = 'SELECT_DIFFICULTY';

/* TIME */
export const SET_TIME = 'SET_TIME';

/* ENTIRE STATE */
export const RESET_GAME_STATE = 'RESET_GAME_STATE';
